local inside_gameobject = require("main.inside_gameobject")
go.property("event", hash(""))
go.property("target", hash(""))

function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("click") and action.pressed then
		if inside_gameobject("#sprite", action.x, action.y) then
			msg.post(self.target, self.event, {x=action.x, y=action.y})
			go.delete()
		end
	end
end
