function init(self)
	msg.post(".", "acquire_input_focus")

	-- Top priority in the render ordering
	gui.set_render_order(15)
	
	-- Cursor node
	self.node = gui.get_node("node")
	
	-- hide os cursor
	defos.set_cursor_visible(false)	

	self.cursor_active = true
end

function on_input(self, action_id, action)
	if action_id == hash("click") then
		if self.cursor_active then
			if action.pressed then
				gui.play_flipbook(self.node, "cursor3")
			end

			if action.released then
				gui.play_flipbook(self.node, "cursor1")
			end
		end
	end

	gui.set_position(self.node, vmath.vector3(action.x+12, action.y-7, 1))
end

function on_message(self, message_id, message, sender)
	if message_id == hash("stop_game") then
		self.cursor_active = false
		gui.play_flipbook(self.node, "cursor1")
	end
	if message_id == hash("restart_game") then
		self.cursor_active = true
	end
end