function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("click") and action.pressed then
		if gui.pick_node(gui.get_node("play"), action.x, action.y) then
			msg.post("/collections#main", "load_screen", {
				name = "house_front",
				pos = vmath.vector3(422,311,0),
				rot = vmath.quat_rotation_z(math.rad(87.222))
			})
		end
	end
end